### PR TITLE
Protobuf implementation

### PR DESCRIPTION
**Pull request by sbrandon96**
Pull request made to test GitHub actions and prepare for next assignment.

### CODE REVIEW

**Comment by sbrandon96** [comment]
Looks like my attempt to resolve the conflicts has DOUBLED the build errors. I will now pay for my ignorance and line by line fix them. Wish me luck.

**Comment by sbrandon96** [comment]
It is my belief that the Java CI with Gradle task will not work and will never work unless build folder contents are pushed into the branch, as these contain generated proto files necessary to complete the build. I am unsure of how to reconcile this. I am an island.

**Comment by sbrandon96** [comment]
The Checkstyles check will be near impossible to properly scrutinize unless we line by line all the generated code. There are a few hundred new errors to consider. Not sure if there is a way to ignore checkstyle for specific files. Will research.

**Comment by sbrandon96** [comment]
After hours of contemplation and consideration, it would appear that are chief issues are as follows:

1) gRPC services and server implementation is incomplete, will remediate and attempt to salvage. Just not sure how to send those stubs across the network boundary. 
2) Added TestProgramImplementation.java to test the run function of our program. Output is correct, but formatting needs adjusted.
3) The dynamic programming approach was wonderful and will definitely speed up the AVL computation, great work! Will have to update after we figure out benchmarking. (May need Main to run)
4) Front end implementation? Not sure if we are just gonna go command line or want to try for a Java GUI or HTML/Web front end. Either way, I am blessed to be here, and tomorrow will be better.

**Comment by sbrandon96** [comment]
Test failures: testProgramImplementattion - just experimenting with different run methods, though today we confirmed that our output is fine, its just that we have to fix the rushing threads.

testMultiUser - fails despite new code from new branch. Will have to copy raw code from source again and double check that it is correct.

Note: Generated files from proto wont push. Make sure to generateProto with gradle when testing and running code independently.

**Review by Youssup — APPROVED** [review]
Dynamic Programming Implemented to make the computation faster

**Pull request merged**
